### ISSUE TITLE
Crash server

### ISSUE THREAD

**Issue by Kerimengit** [Mikusch/fortress-royale#29]
I get a server crash after a few minutes of playing with the error

L 01/04/2021 - 09:30:08: [SM] Blaming: royale.smx
L 04/01/2021 - 09:30:08: [SM] Call stack trace:
L 01/04/2021 - 09:30:08: [SM] [0] GetEntProp
L 01/04/2021 - 09:30:08: [SM] [1] Line 705, royale / stocks.sp :: TF2_GiveNamedItem
L 01/04/2021 - 09:30:08: [SM] [2] Line 40, royale / loot / loot_callbacks.sp :: LootCallback_CreateWeapon
L 04/01/2021 - 09:30:08: [SM] [4] Call_Finish
L 01/04/2021 - 09:30:08: [SM] [5] Line 261, royale / loot / loot.sp :: Loot_BreakCrate
L 01/04/2021 - 09:30:08: [SM] [6] Line 172, royale / loot / loot.sp :: EntityOutput_OnBreakCrateTargetname
L 01/04/2021 - 09:30:08: [royale.smx] Unable to call function for LootType '0' class '8'

**Comment by Mikusch** [comment]
The server crash is unrelated to that error, pretty sure. Looks like it failed to create a Spy weapon for some reason.
Did you alter the config or any convars?

**Comment by Kerimengit** [comment]
No, I did not change anything, I installed this plugin and its extensions and ran on the map, the crash happens after a random time maybe in 3 minutes, maybe in 8 minutes, I tried to find the problem well, I only found this error log when crashing, more I can't say anything about it

**Comment by Mikusch** [comment]
For future reports, I suggest installing [Accelerator](https://forums.alliedmods.net/showthread.php?t=277703), which will upload and analyze crash dumps. This is the only way for us to identify the cause of the crash.

**Comment by Kerimengit** [comment]
I have this thing, I'll throw you the error code K5PU-N4AM-A7XQ
