### ISSUE TITLE
Crash after mapchange

### ISSUE THREAD

**Issue by EduardoKdinho** [Mikusch/fortress-royale#37]
I am realizing that after changemap the server crashes constantly, sometimes at the time of  changelevel, sometimes during the round.

I did tests with and without any plugins and continues with the same problem, currently I use only sourcebans, serverhop, help menu and nothing more complex. I had some skins installed and reduced the number to 4 to avoid problems with too many instaled vtf's .

I installed the accelerator to follow the crash reports, but I don't have the knowledge to understand what the causes are. If you can help me with the solution I would appreciate it.

Here are some of the latest reports:

https://crash.limetech.org/br5ab6bygv7d
https://crash.limetech.org/orjlyidl3epx
https://crash.limetech.org/s5qbr7zzuffa
https://crash.limetech.org/qvbdouqt74nx
https://crash.limetech.org/wun236pyc5ve 

Thank you

**Comment by Mikusch** [comment]
I know we don't really have version numbers yet, but is this the latest version? What map(s) were used?

**Comment by EduardoKdinho** [comment]
> I know we don't really have version numbers yet, but is this the latest version? What map(s) were used?

Latest version, crash with any map when change.

Start ok, no problem with any map, but crash if I use changelevel or with change with mapchooser or rtv or with timelimit/round limit.
