### ISSUE TITLE
Cant use spell attribute.

### ISSUE THREAD

**Issue by cfnnit** [Mikusch/fortress-royale#44]
like SPELL: set item tint RGB:4;
SPELL":"

blah.

L 04/18/2021 - 23:08:17: [SM] Exception reported: TF2Attrib_SetByName: Attribute 'SPELL' not valid

**Comment by FortyTwoFortyTwo** [comment]
Could've explained more in depth what you're trying to do with specific problems, but I see it now.

Loot Table config allows weapon to spawn with attribute, eg medigun has this:
```
			"param"
			{
				"key"	"attributes"
				"value"	"generate rage on heal:1"
			}
```

What you're trying to do is to add attribute name `SPELL: set item tint RGB` with value 4
```
			"param"
			{
				"key"	"attributes"
				"value"	"SPELL: set item tint RGB:4"
			}
```

This creates a problem that `:` is in `value` twice, plugin can't read it correctly. So we would have to either replace attribute name to attribute id, or replace `:` splitting to something else, perhaps `|`
