### ISSUE TITLE
cant use "single wep deploy time increased" atttribute

### ISSUE THREAD

**Issue by cfnnit** [Mikusch/fortress-royale#45]
L 05/29/2021 - 20:56:04: [royale.smx] Malformed attribute string 'single wep depl'

whats wrong?
there are no typos.

**Comment by FortyTwoFortyTwo** [comment]
Could you post config of your attempted attrib to apply here, [like what I said earlier](https://github.com/Mikusch/fortress-royale/issues/44#issuecomment-823411350).

I imagine attrib name was too long to store, but code seems to already accept lengthy attrib names (up to 64 chars).

**Comment by cfnnit** [comment]
> Could you post config of your attempted attrib to apply here, [like what I said earlier](https://github.com/Mikusch/fortress-royale/issues/44#issuecomment-823411350).
> 
> I imagine attrib name was too long to store, but code seems to already accept lengthy attrib names (up to 64 chars), so something must've went wrong.

I think caused by [this](https://github.com/Mikusch/fortress-royale/blob/2205b45c6dea5180b20c3fad1696d8de48ab588a/addons/sourcemod/scripting/royale/loot/loot_callbacks.sp#L96) 

if over 15 it makes error
L 05/27/2021 - 10:54:13: [royale.smx] Malformed attribute string 'mult_dmgtaken_a'
L 05/27/2021 - 10:54:30: [royale.smx] Malformed attribute string 'mult_dmgtaken_a'
L 05/27/2021 - 10:55:37: [royale.smx] Malformed attribute string ''
L 05/27/2021 - 11:01:26: [royale.smx] Malformed attribute string ''
L 05/27/2021 - 11:01:38: [royale.smx] Malformed attribute string ''
L 05/27/2021 - 11:02:07: [royale.smx] Malformed attribute string ''

like this

**Comment by FortyTwoFortyTwo** [comment]
> I think caused by [this](https://github.com/Mikusch/fortress-royale/blob/2205b45c6dea5180b20c3fad1696d8de48ab588a/addons/sourcemod/scripting/royale/loot/loot_callbacks.sp#L96)
> 
> if over 15 it makes error

15 is for how many different attribs can be applied at once, which should be 20 as it's tf2 max allowed attribs.
But the problem I see is that `value` is [above overall max string, which is 256](https://github.com/Mikusch/fortress-royale/blob/2205b45c6dea5180b20c3fad1696d8de48ab588a/addons/sourcemod/scripting/royale.sp#L49).

Could go lazy and increase max string to 512 or 1024, or allow unlimited max string which would require dynamic memory stuff. I'm leaning for the latter.

**Comment by cfnnit** [comment]
[loot.zip](https://github.com/Mikusch/fortress-royale/files/6564723/loot.zip)

here is loot.cfg
