### ISSUE TITLE
item fell through the floor in br_mario

### ISSUE THREAD

**Issue by BLessedDed** [Mikusch/fortress-royale#5]
![btw](https://user-images.githubusercontent.com/58532850/89102753-72dcf200-d40c-11ea-8f02-abe48449201b.JPG)

A shield specifically fell through the floor right here

**Comment by Mikusch** [comment]
This is a map issue due to the creator moving the entire map slightly up, making our current config place crates inside the ground. Resolved with ``br_mario_a7``.
